name: Waka Readme

on:
    workflow_dispatch:
    schedule:
        # Runs every 4 hours
        - cron: "0 */4 * * *"

jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: athul/waka-readme@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
